<!-- <h1>HBJI</h1>
<p>Donc tu as compri ca c'est moi 
    Je suis née a Makhatchkala!
    Emmmmm c'est ou ça ?
    et bien au fans fond de la Russie 
    Ma region est entouré des pays tel que Georgie ,Turqui,Iran
    C'est de la mer(Mer Caspienne) de chez moi  que vient le fameux caviar russe!
    Eh bien je suis venue en France à 14 ans,sans famille parce que je le voulais.
</p>
<p>J'ai eu mon brevet au bout d'un an 
    Puis j'ai enchainé un bac pro cuisine que j'ai eu 
    C'etait pour ça que j'etais venue en France!
    J'ai travaillé 2 ans en tout en cuisine et j'ai vite grave les echellons 
    au bout de 3 mois j'étais déjà chef de partie
    J'ai adoré faire ça 
    Mais il a fallu que le vent tourne ......
</p>
<p>
    Pour me ramener dans le monde de l'informatique 
    J'ai commencé avec OpenClassroom comme tout le monde je crois 
    BigUp a Matthieu Nebra
</p> -->



<div class="container">
  <div class="mySlides">
    <div class="numbertext">1 / 5</div>
    <img src="img/me.jpg">
  </div>

  <div class="mySlides">
    <div class="numbertext">2 / 5</div>
    <img src="img/me1.jpg">
  </div>

  <div class="mySlides">
    <div class="numbertext">3 / 5</div>
    <img src="img/me2.jpg">
  </div>
    
  <div class="mySlides">
    <div class="numbertext">4 / 5</div>
    <img src="img/me3.jpg">
  </div>

  <div class="mySlides">
    <div class="numbertext">5 / 5</div>
    <img src="img/me4.jpg">
  </div>

  <a class="prev" onclick="plusSlides(-1)">❮</a>
  <a class="next" onclick="plusSlides(1)">❯</a>
  <h4>Bon tu as compri ca c'est moi</h4>


