<p>Bonjour <?= htmlspecialchars($_SESSION['auth']) ?></p>
<p>Ca a l'air simple mais avant que tu puisse arriver sur cette page la il m'as 
    fallu des heures de travail pour tout sécuriser et envoyer dans la base de données.
    Pour l'inscription j'ai utilisé INSERT
    Pour la connexion j'ai utilisé SELECT
    Pour afficher ton pseudo et potentiellemnt modifier une des info que tu m'as donné 
    j'ai utilisé UPDATE 
    Puis si jamais tu veux effacer ton compte j'utilise le DELETE</p>
    <p>Mais avant de faire tout ça il faut tout sécuriser en php
    Puisqu'on apprend <strong> NEVER TRUST USER INPUT</strong> a part mettre des conditions d'insertion
    dur les input j'ai aussi utilisé les htmlentities et un droit d'acces limité sur la page <strong>Mon compte</strong><p>

    <p>Ici je te propose de tester tout ça en essayant de modifier ton mot de passe par example</p>

    <form class="crudForm" method="POST">
    <div class="form-group accountForm">
        <input  class="form-control" type="password" name="password" placeholder="Changer le mot de passe"/>
    </div>
    <div class="form-group accountForm">
    <input class="form-control" type="password" name="password_confirm" placeholder="Confirmer le mot de passe"/>
    <span class='formErrors'><?php if(isset ($errors)){echo $errors;}?></span><br/>
    </div>
 
    <button class="btn btn-primary">Changer le mot de passe</button>
    <button class="btn btn-danger" name="deleteUser">Effacer le compte</button>

</form>


    