HTML SCSS JSResult Skip Results Iframe
<div class="section-transition">
  <div class="deck deck1 js-split">
    <div class="bg top">
      <h1 class="split-text">Scroll to see some magic.</h1>
    </div>
    <div class="bg bottom">
      <h1 class="split-text">Scroll to see some magic.</h1>
    </div>
  </div>
  <div class="deck deck2">
    <h1 class="dark centered">New <br />section <br />revealed.</h1>
  </div>
</div>

<div class="deck"></div>
<div class="footer">
  <h2 class="dark">That's all folks!</h2>
  <p class="dark">See another version, with time-based animation: <a href="https://codepen.io/vajkri/pen/GoXjzP" target="_blank">https://codepen.io/vajkri/pen/GoXjzP</a></p>
</div>