<!-- TEXT SCROLL  -->
<div class="text-scroll">
  <div class="line-1">
    <h1>Aïna</h1>
  </div>
  <div class="line-2">
    <h1>LAGRANDE</h1>
  </div>
</div>


<!-- IMG PORTFOLIO  -->

    <div class="img-portfolio">
      <div class="img1"></div>
      <div class="img2"></div>
      <div class="img3"></div>

      <div class="autotext-container">
        <h2 id="autotext"></h2>
      </div>
    </div>



  <!-- PARCOURS  -->
<div class="birth-box">
  <!-- BANDE DEROULANTE -->
<div class="marquee parcour">
  <div class="marquee__inner" aria-hidden="true">
    <span>Parcours</span>
    <span>Parcours</span>
    <span>Parcours</span>
    <span>Parcours</span>
  </div>
</div>

<!--************* FIRST SECTION  ***************-->

  <div class="birth reveal-">
      <h5>Je m'appelle Aïna AKAGADZHIEVA.<br/>
      Je me nomme aussi <strong>Aïna LAGARANDE</strong> non pour mon ego démesuré,
      mais pour une autre raison.<br/>
      Je suis née à <strong> Makhatchkala</strong>  le 20 avril 1999.<br>
      Hein, ou ça?
      Makhatchkala est une petite ville de sud de la <strong>Russie</strong> entouré 
      de Georgie,Iran,Turquie à côté de la mer Caspienne.<br/>
      Malgré une vie heureuse, ma mère comprends vite que mon potentiel sera vite étouffé dans ce bled et 
      à l'âge de 14 ans, elle m'envoie en France pour devenir cuisinière.</h5>
      <img class="little-me-img" src="img/little3.jpg" alt="photo d'enfance">
  </div>

<!--************* SECOND SECTION  ***************-->

   <div class="birth reveal-">
      <h5> J'ai fait mes études de <strong>cuisine</strong>  à <strong>Saint Méen le Grand</strong>  et
       j'ai vite gravé les échelons pour au final devenir <strong>chef de partie</strong> 
        d'un restaurant bistronomique  à Rennes.<br/><br/>
        <a href="https://www.ouest-france.fr/bretagne/saint-meen-le-grand-35290/de-la-russie-la-france-l-aventure-d-aina-5715568"
        class="link-animation">
        Ici un article fait pendant mes études</a>
      </h5>
      <img class="hover-img-effect" src="img/kit1.jpg" alt="">
  </div>

<!--************* THIRD SECTION  ***************-->

  <div class="birth reveal-">
      <h5>Puis,
        j'ai pris une année de repos pour <strong>remplir les objectifs</strong>  que la vie de chef ne me permettait pas de
        remplir.
        <ul>
          <li>J'ai passé mon permis.</li>
          <li>J'ai voyagé.</li>
          <li> J'ai appris un nouveau métier, celui de développeuse Web.</li>
        </ul>
        </h5>
      
      <img class="break-img" src="img/book.jpg" alt="image de livre">
      <img class="back-img" src="img/take1.svg" alt="image svg take it easy">
  </div>
</div>

</div>


<!-- SKILLS  -->
 
  <div class="skills-text reveal-">
    <h5> J'ai commencé comme tout le monde sur <strong>openclassroom en autodidacte</strong>  pendant 7 mois.</h5>
    <h5>Puis j'ai voulu aller plus loin et j'ai donc fait une <strong>formation</strong>  intense de 3 mois
    avec <strong>3 W Académie.</strong></h5> 
    <h5>Aujourd'hui, je suis développeuse Web Junior <strong>diplômée</strong>.</h5>
    <h5>J'ai autant de compétences en <strong>Front</strong> qu'en <strong> Back</strong>.</h5>
    <h5>Je ne suis pas la plus forte, mais <strong>je fais de mon mieux</strong> pour avoir le résultat.</h5>
    <h5> J'imagine que mon premier boulot me dirigera vers la développeuse que je deviendrais.</h5>
    <h5>Je vous avoue que je doute beaucoup de mes capacités, j'ai une sorte de syndrome d'imposteur.</h5>
    <h5>Mais j'ai décidé d'aller jusqu'au bout de ce parcours parce que j'en suis capable.</h5>
  </div>

  <!-- BANDE DEROULANTE -->
  <div class="marquee">
  <div class="marquee__inner" aria-hidden="true">
    <span>SKILLS</span>
    <span>SKILLS</span>
    <span>SKILLS</span>
    <span>SKILLS</span>
  </div>
</div>

<!-- SKILLS LAPTOP ANIMATION -->

<ul class="skills-items">
    <li>HTML5</li>
    <li>CSS3/SASS/BOOTSTRAP</li>
    <li>JS</li>
    <li>PHP/MVC</li>
    <li>MySQL/CRUD</li>
    <li>GIT</li>
    <li>SEO</li>
  </ul>

  <div id="scene">
    <div id="box-container">
      <div id="box-front"><i class="fab fa-js fa-8x"></i></div>
      <div id="box-back"><i class="fab fa-html5 fa-8x"></i></div>
      <div id="box-left"><i class="fab fa-css3-alt fa-8x"></i></div>
      <div id="box-right"><i class="fab fa-php fa-8x"></i></div>
      <div id="box-bottom"><i class="fab fa-git-alt fa-8x"></i></div>
      <div id="box-top"><i class="fab fa-sass fa-8x"></i></div>
    </div>
  </div>


<!-- SKILLS MOBILE ANIMATION -->
<div class="mobil-first-bar-prgress">
  <div class="skills">
  <!-- ******************************HTML PROGRESS BAR*************************** -->

  <div class="HTMLProgressBar">
    <div class="myBarHTML">
      <p class=labelCode>HTML5</p>
    </div>
  </div>
  <!-- ******************************CSS PROGRESS BAR*************************** -->

  <div class="CSSProgressBar">
    <div class="myBarCSS">
        <p class=labelCode>CSS3/SASS/BOOTSTRAP</p>
    </div>
  </div>
  <!-- ******************************JS PROGRESS BAR*************************** -->

  <div class="JSProgressBar">
    <div class="myBarJS">
        <p class=labelCode>JavaScript</p>
    </div>
  </div>
  <!-- ******************************PHP PROGRESS BAR*************************** -->

  <div class="PHPProgressBar">
    <div class="myBarPHP">
        <p class=labelCode>PHP/MVC</p>
    </div>
  </div>
  <!-- ******************************SEO PROGRESS BAR*************************** -->

  <div class="SQLProgressBar">
    <div class="myBarSQL">
        <p class=labelCode>MySQL/CRUD</p>
    </div>
  </div>
  <!-- ******************************WPPROGRESS BAR*************************** -->

  <div class="GITProgressBar">
    <div class="myBarGIT">
        <p class=labelCode>GIT</p>
    </div>
  </div>
  </div>
</div>
<script src="../portfolio/js/progress-bar.js"></script>

 <!-- ****************** CONTACT ****************** -->
  <!-- BANDE DEROULANTE -->

 <div id="contact-location" class="marquee">
  <div class="marquee__inner" aria-hidden="true">
    <span>Contact</span>
    <span>Contact</span>
    <span>Contact</span>
    <span>Contact</span>
  </div>
</div>
  <!-- CONTACT FORM -->

<div id="contact">
    <form  method="POST" class="contactForm">
      <div class="forms">
        <label class="formLabel" for="name">Nom</label>
        <input class="nameInput" name="name" type="text" id="name" >
        <span class='formErrors'><?php if(isset ($errorName)){echo $errorName;}?></span><br/>
    <span class='formErrors'><?php if(isset ($errorNameLenght)){echo $errorNameLenght;}?></span>
      </div>
    
      <div class="forms">
        <label class="formLabel" for="email">Email</label>
        <input class="emailInput" name="email" type="email" id="email" >
        <span class='formErrors'><?php if(isset ($errorEmail)){echo $errorEmail;}?></span>
      </div>

      <div class="forms">
        <label class="formLabel" for="phone">Tel:</label>
        <input  class="phoneInput" name="phone" type="tel" id="phone" >
        <span class='formErrors'><?php if(isset ($errorPhone)){echo $errorPhone;}?></span>
      </div>

      <div class="forms">
        <label class="formLabel" for="message">Message</label>
      <textarea class="textareaInput" type="text" name="message" id="message" ></textarea>
      <span class='formErrors'><?php if(isset ($errorMessage)){echo $errorMessage;}?></span>
     <span class='formErrors'><?php if(isset ( $emptyError)){echo  $emptyError;}?></span>
      </div>
      <button name="contactFormButton" type="submit" class="submitButton">Envoyer</button>
    </form>

  <!-- CONTACT INFO  SECTION -->
  <div class="infos-contact reveal-">
    <p>Sinon je suis présente sur les réseaux sociaux </p>
    <p>Je t'invite également à consulter mon compte GitHub </p> 
    <p>Tel: +33 6 23 69 69 84</p>
    <p>Mail:ainapukipuki@gmail.com</p>
    <p>Site Web: <a href="https://www.ainaweb.site/" class="link-animation">www.ainaweb.site</a></p>


  <!-- SOCIAL NETWORKS -->
      <div class="social-networks">
        <ul>
          <li><a href="https://www.linkedin.com/in/a%C3%AFna-lagrande-9683801b9/"><i class="fab fa-linkedin fa-3x"></i></a></li>
          <li><a href="https://www.instagram.com/ainaweb.site/"><i class="fab fa-instagram fa-3x"></i></a></li>
          <li><a href="https://github.com/aina200"><i class="fab fa-github fa-3x"></i></a></li>
          <li><a href="https://gitlab.com/aina200"><i class="fab fa-gitlab fa-3x"></i></a></li>
          <li><a href="https://codepen.io/aina200"><i class="fab fa-codepen fa-3x"></i></a></li>
        </ul>
      </div>
  </div>
</div>
