<!-- TEXT SCROLL  -->

<div class="text-scroll">
  <div class="line-1">
    <h1>Aïna</h1>
  </div>
  <div class="line-2">
    <h1>LAGRANDE</h1>
  </div>
</div>

<!-- IMG PORTFOLIO  -->

    <div class="img-portfolio">
      <div class="imgRotate1"></div>
      <div class="imgRotate2"></div>
      <div class="imgRotate3"></div>
    </div>

<h2 id="autotext"></h2>


<!-- PARCOURS  -->
<div class="birth-box">

  <div class="birth">

    <h5>Je m'appelle Aïna AKAGADZHIEVA
    Je me nomme aussi <strong>Aïna LAGARANDE</strong>  grace à  mon compagnon 
     qui me nomme comme ça si je doute de moi même.
    Je suis née à <strong> Makhatchkala</strong>  le 20 avril 1999.<br>
    Hein,Ou ça?
    Makhatchkala est une petite ville de sud de la <strong>Russie</strong> entouré 
    de Georgie,Iran,Turquie à coté de la mer Caspienne
    Malgré une vie heureuse ma mére comprends vite que mon potentiel dépasse ce bled et 
    à l'age de 14 ans elle m'envoie en France pour devenir cuisiniere</h5>
    <img class="little-me-img" src="img/little3.jpg" alt="photo d'enfance">
  </div>

   <div class="birth">
    <h5> J'ai fait mes etudes de <strong>cuisine</strong>  à <strong>Saint Méen le Grand</strong>  et
       j'ai vite gravé les echellons pour au final devenir <strong>chef de partie</strong> 
        d'un restaurant bistronomique  à Rennes.<br/><br/>
        <a href="https://www.ouest-france.fr/bretagne/saint-meen-le-grand-35290/de-la-russie-la-france-l-aventure-d-aina-5715568">
        Clique ici si tu veux lire l'article sur moi datant de 2018</a>
      </h5>
      <img class="hover-img-effect" src="img/kit1.jpg" alt="">
      <!-- ici :hover de la deuxieme photo -->
  </div>

  <div class="birth">
    <h5>Puis,
      j'ai pris une année de repos pour <strong>remplir les objectif</strong>  que la vie de chef ne me permattais pas de
       remplir.
      <ul>
        <li>J'ai passé mon permis.</li>
        <li>J'ai voyagé.</li>
        <li> J'ai appris un nouveau métier, celui de developpeuse Web.</li>
      </ul>
    </h5>
      <img class="break-img" src="img/book.jpg" alt="">
      <!-- autor de limage mettre un text qui tourne autour de limage -->
  </div>
</div>

<!-- SKILLS  -->
 <!-- sur cette section rajouter un truc en js comme ouverture de scene -->
  <div class="skills-text">
    <h5> J'ai commncé comme tout le monde sur <strong>openclassroom en autodidacte</strong>  pendant 7 mois.</h5>
    <h5>Puis j'ai voulu aller plus loin et j'ai donc fait une <strong>formation</strong>  intense de 3mois
   avec <strong>3W Académie</strong></h5> 
   <h5>Aujourd'hui je suis développeuse Web Junior <strong>diplomée</strong> .</h5>
   <h5>J'ai autant de compétences en <strong>Front</strong> qu'en <strong> Back</strong>.</h5>
   <h5>Je ne suis pas la plus forte,mais <strong>je fais de mon mieux</strong> pour avoir le résultat.</h5>
  </div>


<section>
 <h3 data-speed="-5" class="layer">HTML5</h3>
 <h3 data-speed="-11" class="layer">CSS</h3>
 <h3 data-speed="-12" class="layer">JavaScript</h3>
 <h3 data-speed="-6" class="layer">PHP</h3>
 <h3 data-speed="-8" class="layer">GIT</h3>
 <h3 data-speed="-2" class="layer">MVC</h3>
 <h3 data-speed="-4" class="layer">CRUD</h3>
 <h3 data-speed="-9" class="layer">MySQL</h3>
 <h3 data-speed="-16" class="layer">SEO</h3>
 <h3 data-speed="-7" class="layer">BOOTSTRAP</h3>
 <h2 data-speed="2" class="layer">MES SKILLS</h2>
</section>












<!-- 
      <section class="scrollingTxt">
        
      <p class="result"></p>
     <script src="./js/text.js"></script>
      </section> -->

      











<!-- <p>


   J'imagine que mon premier boulot me dirigera vers la développeuse que je devienderai
   Je vous avoue que je doute beaucoup de mes capacités surtout quand je vois mes collegues qui me semblent etre 
   plus competens que moi .
   Mais j'ai decidé d'aller jusqu'au bout de ce parcours
   Parcequ'a vrai dire une fois que je l'ai decidé il n'ya plus de retour en arriere.
   Tout en bas laisser les langues centre d'interet et contact
</p> -->
