<header>
<img class="card-img-overlay" src="img/svg4.svg" alt="">
    <div class="homeText">
        <h2 class="text-center">Bonjour à toi!</h2>
        <h3 class="text-center">Moi c'est Aïna LAGRANDE</h3>
        
    </div>

    <div class="homePhoto">
        <div class="photoBorder">
            <img  class="photoPro" src="img/photopro.jpeg" alt=""/>
        </div>
        <h3 class="text-center">Ici tu verra mes compétences <br> mis en oeuvres en front et back end </h3>
    </div>

    <div class="photoSquare"></div>
</header>