<!--****************** INTRODUCTION ****************-->
<div class="intro">
    <div class="intro-text">
        <h1 class="hide">
            <span class="text">Le Portfolio d'une </span>
        </h1>
        <h1 class="hide">
            <span class="text">Développeuse Web Junior</span>
        </h1> 
    </div>
</div>
<div class="slider"></div>

<!-- ************ HEADER FROM HOMEPAGE ****************-->
<header>
    <div class="homeText">
        <h3 class="text-center reveal-1">Moi c'est Aïna LAGRANDE</h3>
        <h3 class="text-center reveal-3">Ici, tu verra mes compétences <br> mis en œuvres en front et back end </h3>
    </div> 
    <div class="img-homepage">
        <img  class="photoPro" src="img/photopro.jpeg" alt="photo professionnelle"/>
    </div>
</header>
