
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8"/>
    <meta name="description" content="Portfolio Aina LAGRANDE"/>
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width,initial-scale=1"/> 
    <title>Portfolio Aina LAGRANDE</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	  <link rel="stylesheet" type="text/css" href="../portfolio/css/style.css">
  </head>

<body>
 <!-- ********************NAVBAR************************ -->
<nav class="nav-menu">
  <ul>
    <li><a href="index.php?page=homepage" class="link-animation">Acceuil</a></li>
    <li><a href="index.php?page=frontend" class="link-animation">Côté Front-end</a></li>
    <li><a href="index.php?page=backend" class="link-animation">Côté Back-end</a>
    
    <span onclick="subMenu()"><i class="fas fa-chevron-right"></i></span>
    <ul class="sub-menu">
    <?php if(isset($_SESSION['auth'])): ?>
      <li><a href="index.php?page=logout" class="link-animation">Se déconnecter</a></li>
      <li><a href="index.php?page=account" class="link-animation">Mon compte</a></li>
      <?php else: ?>
        <li><a href="index.php?page=backend#register-location" class="link-animation">S'inscrire</a></li>
      <li><a href="index.php?page=login" class="link-animation">Se connecter</a></li>
      
      <?php endif; ?>
    </ul>
    </li>
    <li><a href="index.php?page=frontend#contact-location" class="link-animation">Contact</a></li>
  </ul>
</nav>

<!-- BURGER MENU FOR MOBIL RESOLUTION -->
<div class="btn_menu">
  <span class='toggle'></span>
</div>


  <main>
        <?php require $page ?>
  </main>

    <script src="https://unpkg.com/typewriter-effect@latest/dist/core.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.0/gsap.min.js" 
    integrity="sha512-1dalHDkG9EtcOmCnoCjiwQ/HEB5SDNqw8d4G2MKoNwjiwMNeBAkudsBCmSlMnXdsH8Bm0mOd3tl/6nL5y0bMaQ==" 
    crossorigin="anonymous">
    </script>
   <script src="../portfolio/js/app.js"></script> -->
   <script src="../portfolio/js/menu.js"></script>
   <script src="../portfolio/js/text.js"></script>

</body>
</html>
