
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8"/>
    <meta name="description" content="Portfolio Aina LAGRANDE"/>
    <meta name="robots" content="index,follow">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio Aina LAGRANDE</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	  <link rel="stylesheet" type="text/css" href="css/style.css">
  </head>
<body>


 <!-- ********************NAVBAR************************ -->

<nav>
  <ul>
    <li><a href="index.php?page=homepage">Acceuil</a></li>
    <li><a href="index.php?page=frontend">Côté Front-end</a></li>

    <li><a href="index.php?page=backend">Côté Back-end</a>
    <span onclick="subMenu()"><i class="fas fa-chevron-right"></i></span>
    
    <ul class="sub-menu">
      
      <?php if(isset($_SESSION['auth'])): ?>
      <li><a href="index.php?page=logout">Se déconnecter</a></li>
      <li><a href="index.php?page=account">Mon compte</a></li>
      <?php else: ?>
        <li><a href="index.php?page=backend">S'inscrire</a></li>
      <li><a href="index.php?page=login">Se connecter</a></li>
      
      <?php endif; ?>
    </ul>

    </li>
  </ul>
</nav>


  <main>
        <?php require $page ?>
  </main>

  <script src="./js/app.js"></script>
</body>
</html>
