
<form class="crudForm" method="POST">
  <div class="mb-3">
    <label for="exampleInputEmail2" class="form-label">Pseudo</label>
    <input type="text" name="userName" class="form-control" id="exampleInputEmail2">
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword2" class="form-label">Password</label>
    <input type="password" name="password" class="form-control" id="exampleInputPassword2">
  </div>
  <span class='formErrors'><?php if(isset ($errors)){echo $errors;}?></span><br/>

  <button type="submit" class="btn btn-primary">S'inscrire</button>
</form>